language: cpp
compiler: g++
language: erlang
otp_release:
  - 23.0

matrix:
  include:
    - os: linux
      addons:
        apt:
          update: true
          sources:
            - sourceline: 'ppa:mhier/libboost-latest'
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - gcc-10
            - g++-10
            #- boost-latest
            - boost1.74
            - libxslt1.1
            - python-lxml
            - doxygen
      env:
        - MATRIX_EVAL="CC=gcc-10 && CXX=g++-10"

before_install:
  - eval "${MATRIX_EVAL}"

before_script:
  - echo "DIR:BUILD=/tmp/${USER}/utxx"                           > .cmake-args.$(hostname)
  - echo "DIR:INSTALL=/tmp/${USER}/install/@PROJECT@/@VERSION@" >> .cmake-args.$(hostname)
  - echo "PKG_ROOT_DIR=/usr/local"                              >> .cmake-args.$(hostname)
  - echo "BOOST_INCLUDEDIR=/usr/include"                        >> .cmake-args.$(hostname)
  - echo "BOOST_LIBRARYDIR=/usr/lib/x86_64-linux-gnu"           >> .cmake-args.$(hostname)
  - echo "CMAKE_CXX_COMPILER=${CXX}"                            >> .cmake-args.$(hostname)

script:
  - ${CXX} --version
  ############################################################################
  # Install a recent CMake (unless already installed on OS X)
  ############################################################################
  - cd ${TRAVIS_BUILD_DIR}      # Go back to the root of the project and bootstrap
  - make bootstrap generator=make build=Debug
  - make
  - make doc > build/doc.log
  - make install
  - make test
branches:
  only: master
